services:
  backend:
    build: ./backend
    container_name: biblioteca_backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: biblioteca_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: biblioteca_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    container_name: biblioteca_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana
    container_name: biblioteca_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus